CREATE TABLE ganr (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), name VARCHAR(50));

CREATE TABLE avtor (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), name VARCHAR(50));

CREATE TABLE sbook (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), name VARCHAR(50), opisanie VARCHAR(50), cena INT );

CREATE TABLE book_avtor (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), idbook INT, idavtor INT );
CREATE TABLE book_ganr (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), idbook INT, idganr INT );

